document.addEventListener("DOMContentLoaded",function(){const scrollContainer=document.querySelector("[data-scroll-web_page]");const navbar=document.querySelector(".header");const isMobile=window.innerWidth<=768;gsap.registerPlugin(ScrollTrigger);let scroller=null;if(!isMobile){scroller=new LocomotiveScroll({el:scrollContainer,smooth:!0,multiplier:1.1,lerp:0.09,getDirection:!0,getSpeed:!0,});scroller.on("scroll",ScrollTrigger.update);ScrollTrigger.scrollerProxy(scrollContainer,{scrollTop(value){return arguments.length?scroller.scrollTo(value,0,0):scroller.scroll.instance.scroll.y},getBoundingClientRect(){return{left:0,top:0,width:window.innerWidth,height:window.innerHeight}},pinType:scrollContainer.style.transform?"transform":"fixed",});new ResizeObserver(()=>scroller.update()).observe(scrollContainer)}
const currentScroller=isMobile?window:scrollContainer;let lastScrollTop=0;if(!isMobile&&scroller){scroller.on("scroll",(args)=>{let scrollTop=args.scroll.y;if(scrollTop>lastScrollTop&&scrollTop>100){navbar.classList.add("scrollUp")}else{navbar.classList.remove("scrollUp")}
lastScrollTop=scrollTop})}else{window.addEventListener("scroll",()=>{let scrollTop=window.pageYOffset||document.documentElement.scrollTop;if(scrollTop>lastScrollTop&&scrollTop>100){navbar.classList.add("scrollUp")}else{navbar.classList.remove("scrollUp")}
if(scrollTop<=10){navbar.classList.remove("scrollUp")}
lastScrollTop=scrollTop<=0?0:scrollTop},{passive:!0})}
function bannerAnimation(){const tl=gsap.timeline({defaults:{ease:"power3.out",opacity:0}});tl.from(".logo, .unorder-list li",{delay:1.5,y:-40,stagger:isMobile?0.08:0.10,duration:isMobile?0.8:0.5,});tl.from(".main-txt",{x:-120,duration:isMobile?1.0:1.5,ease:"power3.out"},"-=0.8");tl.from(".white-btn-galaxy-button-wrapper",{x:-100,duration:isMobile?0.7:0.9},"-=0.9");tl.from(".right-svg",{scale:0.6,duration:isMobile?1.5:1.5,ease:"power3.out"},"-=1");tl.from(".profile-main",{scale:1.15,y:60,duration:isMobile?1.5:1.8,ease:"power3.out"},"-=1")}
bannerAnimation();function aboutSection(){let tl=gsap.timeline({scrollTrigger:{trigger:".about",scroller:currentScroller,start:isMobile?"top 70%":"top 80%",end:isMobile?"bottom 60%":"bottom 70%",scrub:isMobile?1:2.5,},});tl.from(".about-main-heading",{scale:0.8,opacity:0,duration:isMobile?0.6:1.2,ease:"power3.out"}).from(".about-left",{x:-120,opacity:0,duration:isMobile?1.9:1.3,ease:"power3.out"},"-=0.4").from(".about-right h2",{x:120,opacity:0,duration:isMobile?1.9:1.3,ease:"power3.out"},"-=0.5").from(".about-right h3",{y:50,opacity:0,duration:isMobile?1.9:1.2,ease:"power2.out"},"-=0.3").from(".about-right p",{y:30,opacity:0,duration:isMobile?6.1:2.7,stagger:1.15,ease:"power2.out"},"<")}
aboutSection();function skillSection(){gsap.utils.toArray(".skill").forEach((el)=>{gsap.from(el,{scrollTrigger:{trigger:el,scroller:currentScroller,start:isMobile?"top 90%":"top 95%",end:isMobile?"bottom 80%":"bottom 80%",scrub:1.5,},y:isMobile?60:60,opacity:0,duration:isMobile?1.1:1.3,ease:"power3.out",})});let tl=gsap.timeline({scrollTrigger:{trigger:".skill-wrapper",scroller:currentScroller,start:isMobile?"top 97%":"top 97%",end:isMobile?"bottom 50%":"bottom 85%",scrub:1.2,},});tl.from(".skill-wrapper h3, .stuff-align",{scale:0.7,opacity:0,duration:isMobile?1.8:1.1,ease:"power4.out",}).from(".skill-para",{y:25,opacity:0,duration:isMobile?0.7:0.9,ease:"power2.out"},"-=0.5")}
skillSection();function workSection(){gsap.from(".work-section h3",{scrollTrigger:{trigger:".work-section",scroller:currentScroller,start:"top 90%",end:"bottom 70%",scrub:1.3,},scale:0.6,opacity:0,duration:1,ease:"power4.out",});gsap.utils.toArray(".work-item").forEach((item)=>{gsap.from(item,{scrollTrigger:{trigger:item,scroller:currentScroller,start:"top 90%",end:"bottom 70%",scrub:1.8,},y:isMobile?30:50,opacity:0,duration:1.2,ease:"power3.out",})})}
workSection();function CompanySection(){const cards=[{selector:".left-card-one",x:-80}];cards.forEach((card)=>{gsap.from(card.selector,{scrollTrigger:{trigger:card.selector,scroller:currentScroller,start:"top 95%",end:"bottom 80%",scrub:1.8,},x:card.x||0,y:card.y||0,opacity:0,duration:1.2,ease:"power3.out",})});let tl=gsap.timeline({scrollTrigger:{trigger:".company-container",scroller:currentScroller,start:isMobile?"top 70%":"top 97%",end:isMobile?"bottom 50%":"bottom 85%",scrub:1.2,},});tl.from(".company-right h2",{y:40,opacity:0,duration:1,ease:"power3.out"}).from(".company-right h3, .company-right p",{y:25,opacity:0,stagger:0.2,duration:0.8,ease:"power2.out"},"-=0.6").from(".creative-btn-wrapper, .blue_btn",{y:25,opacity:0,stagger:0.2,duration:0.8,ease:"power2.out"},"-=0.5")}
CompanySection();function hobbiesSection(){let tl=gsap.timeline({scrollTrigger:{trigger:".hobbies-wrapper",scroller:currentScroller,start:"top 90%",end:"bottom 80%",scrub:1.8,},});tl.from(".hobbies-wrapper h2",{scale:0.8,opacity:0,duration:1,ease:"power4.out"}).from(".hobbies-image img",{x:isMobile?-40:-100,opacity:0,duration:1.5,ease:"power3.out"},"-=0.2").from(".hoby-items",{x:isMobile?40:80,opacity:0,stagger:0.2,duration:1,ease:"power3.out"},"-=0.2")}
hobbiesSection();function footerSection(){let tl=gsap.timeline({scrollTrigger:{trigger:".contact",scroller:currentScroller,start:"top 95%",end:"bottom 90%",scrub:1.5,},});tl.from(".contact h2",{scale:0.7,opacity:0,duration:1,ease:"power3.out"}).from(".icons",{scale:0.7,opacity:0,duration:1,stagger:0.15,ease:"back.out(1.7)"},"-=0.5").from(".mail-section",{y:40,opacity:0,duration:1,ease:"power2.out"},"-=0.6")}
footerSection();const navLinks=document.querySelectorAll("[data-scroll-to]");navLinks.forEach((link)=>{link.addEventListener("click",function(e){e.preventDefault();const targetId=this.getAttribute("href");const targetEl=document.querySelector(targetId);if(targetEl){if(!isMobile&&scroller){scroller.scrollTo(targetEl,{offset:-50,duration:800})}else{targetEl.scrollIntoView({behavior:"smooth"})}}})});const menuBtn=document.getElementById("menu-btn");const navMenu=document.getElementById("nav-menu");if(menuBtn){menuBtn.addEventListener("click",()=>{navMenu.classList.toggle("active");menuBtn.classList.toggle("active")})}
document.querySelectorAll(".nav-links a").forEach((link)=>{link.addEventListener("click",()=>{navMenu?.classList.remove("active");menuBtn?.classList.remove("active")})});var hidden,visibilityChange;if(typeof document.hidden!=="undefined"){hidden="hidden";visibilityChange="visibilitychange"}else if(typeof document.msHidden!=="undefined"){hidden="msHidden";visibilityChange="msvisibilitychange"}else if(typeof document.webkitHidden!=="undefined"){hidden="webkitHidden";visibilityChange="webkitvisibilitychange"}
var animElements=[document.querySelector(".titlebg"),document.querySelector(".svglogo"),];function togglePlayState(isHidden){animElements.forEach((el)=>{if(el)el.classList.toggle("noplay",isHidden);})}
document.addEventListener(visibilityChange,()=>togglePlayState(document[hidden]),!1);animElements[0]?.classList.add("titleanim");window.addEventListener("resize",()=>{ScrollTrigger.refresh();if(!isMobile&&scroller)scroller.update();});ScrollTrigger.addEventListener("refresh",()=>scroller?.update());ScrollTrigger.refresh();setTimeout(()=>{ScrollTrigger.refresh()},5200)})
